### PR TITLE
Save PF and Puppi candidates

### PR DESCRIPTION
**Pull request by jmduarte**
Adding functionality to save PF and PUPPI candidates in perfNano ntuple. This is desired for training ML MET algos based on candidate information.

@gpetruc let me know what suggestions you have. I turned it on right now for testing, but I can have it turned off by default before merging.

cc: @nhanvtran  @therwig @ExcitingSquid

### CODE REVIEW

**Comment by jmduarte** [comment]
@gpetruc one question, I had is if I should expect the L1PF candidates to have puppi weights filled? This seems to be the case, but I would've naively expected these to be some null value. Or maybe these two collections are effectively the same?

**Review by gpetruc — APPROVED** [review]
Hi,
Sorry I had lost track of this PR. 

Indeed the list of candidates are almost the same: the code first fills in the puppiWeight for all PF candidates and then outputs the list of PF and of Puppi (where in the list of Puppi the pT is rescaled from the weights, and the null particles are pruned away).

This is fine for me, but I'd keep it off by default, turning it on with a 'saveCands()' function, since otherwise it probably increases the size of the ntuples by quite a bit.

**Comment by jmduarte** [comment]
Hi @gpetruc  and @therwig, I rebased this PR and made the changes you requested (saving candidates can now be turned on by invoking `saveCands()`)

I also noticed some functionality/examples were dropped from the config (like saving the dump file and the regionalizing). Should we preserve that somewhere? Or is it still there?

**Comment by gpetruc** [comment]
Hi,

> I also noticed some functionality/examples were dropped from the config (like saving the dump file and the regionalizing). Should we preserve that somewhere? Or is it still there?

The dump file functionality is in [L1Trigger/Phase2L1ParticleFlow/test/make_l1ctLayer1_dumpFiles_cfg.py](https://github.com/p2l1pfp/cmssw/blob/L1PF_11_1_7_X_newfirmware/L1Trigger/Phase2L1ParticleFlow/test/make_l1ctLayer1_dumpFiles_cfg.py), and the regionalizing is always on as the emulators require it (now that we use HLS datatypes, the range of the eta and phi coordinates is limited and can't span the whole detector anymore)

**Pull request merged**
